### ISSUE TITLE
Solicitud de README.md

### ISSUE THREAD

**Issue by reitmas32** [AbrahamRH/Vim#1]
Hola crees que puedas hacer un pequeño README.md para probarlo?, por que lo he intentado pero no he podido

**Comment by AbrahamRH** [comment]
Claro, en un rato lo hago para que puedas probarlo.

**Comment by AbrahamRH** [comment]
@reitmas32 Listo! si aún hay fallos intentando utilizar la configuración no dudes en decirme. 😉
